### PR TITLE
change background color to black

### PR DESCRIPTION
**Pull request by UlianaKarpash**
Hi Mary! have a look at my change, please

### CODE REVIEW

**Comment by michaelkhersonsky** [comment]
@UlianaKarpash I don't think the color is good. please change to red

**Comment by UlianaKarpash** [comment]
@michaelkhersonsky  Ok

**Comment by MaryDanylova** [comment]
Uliana, change the color as Mickhael said

**Comment by UlianaKarpash** [comment]
@MaryDanylova Ok. I'll do my best

**Comment by UlianaKarpash** [comment]
@michaelkhersonsky please review. I already changed to red

**Review by michaelkhersonsky — APPROVED** [review]
I'm so glad to see this wanderfull page in red

**Pull request merged**
